# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeedUni' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FeedUni
  
  pod 'TimelineTableViewCell'
  pod 'TabPageViewController'
  pod 'RealmSwift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'Toucan'
  pod 'Nuke'
  pod 'Nuke-Toucan-Plugin'
  
end
